name: Metrics
on:
  # Обновлять каждые 24 часа
  schedule: [{cron: "0 0 * * *"}]
  # Или запускать вручную из вкладки Actions
  workflow_dispatch:
  # Или при каждом пуше в ветку master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Ygrick
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Moscow
